//go:build ignore

// gen_unitids.go fetches Grafana's value-format registry at a pinned tag,
// extracts every `id: '…'` declaration, and emits grafana_unitids_test.go: the
// set of every valid Grafana unit ID at that version. Not compiled into the
// plugin.
//
// Usage: go run gen_unitids.go <grafana-tag>  (e.g. v12.1.0)
// Invoked by `go generate ./pkg/plugin/`; emitted file is committed.
package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"slices"
)

const upstreamURLFmt = "https://raw.githubusercontent.com/grafana/grafana/%s/packages/grafana-data/src/valueFormats/categories.ts"
const outputPath = "grafana_unitids_test.go"

// idPattern matches every `id: '<id>'` declaration in categories.ts; upstream
// uses this exact form on every format entry.
var idPattern = regexp.MustCompile(`id: '([^']+)'`)

func main() {
	log.SetFlags(0)
	log.SetPrefix("gen_unitids: ")
	if len(os.Args) != 2 {
		log.Fatalf("usage: go run gen_unitids.go <grafana-tag>  (e.g. v12.1.0)")
	}
	tag := os.Args[1]
	url := fmt.Sprintf(upstreamURLFmt, tag)

	resp, err := http.Get(url)
	if err != nil {
		log.Fatalf("fetch %s: %v", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("fetch %s: %s", url, resp.Status)
	}
	src, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("read body: %v", err)
	}

	matches := idPattern.FindAllSubmatch(src, -1)
	if len(matches) == 0 {
		log.Fatalf("no `id: '…'` matches in %s — upstream format may have changed", url)
	}
	ids := make([]string, 0, len(matches))
	for _, m := range matches {
		ids = append(ids, string(m[1]))
	}
	slices.Sort(ids)
	ids = slices.Compact(ids)

	var out bytes.Buffer
	fmt.Fprintf(&out, fileHeader, tag, url, len(ids))
	for _, id := range ids {
		fmt.Fprintf(&out, "\t%q: {},\n", id)
	}
	out.WriteString("}\n")

	if err := os.WriteFile(outputPath, out.Bytes(), 0o644); err != nil {
		log.Fatalf("write %s: %v", outputPath, err)
	}
	log.Printf("wrote %s (%d IDs from grafana/grafana@%s)", outputPath, len(ids), tag)
}

const fileHeader = `// Code generated by gen_unitids.go; DO NOT EDIT.
//
// Source: grafana/grafana@%[1]s
//   %[2]s
// Upstream copyright Grafana Labs, licensed Apache-2.0. This file contains
// only the set of unit-ID strings extracted from the upstream value-format
// registry — none of the upstream code, structure, or expression is reproduced.
//
// Refresh: edit the //go:generate directive in unit_map_test.go and run
// ` + "`go generate ./pkg/plugin/`" + `.

package plugin

// validGrafanaUnitIDs is the set of every unit ID declared in Grafana's
// value-format registry at the pinned version (%[3]d IDs).
//
// TestUnitMapValuesAreValidGrafanaIDs uses this to guard against typos in
// unitSymbolToGrafanaID — values that look like valid Grafana IDs but are not.
var validGrafanaUnitIDs = map[string]struct{}{
`
