//go:build ignore

// gen.go fetches Grafana's value-format registry at a pinned tag, extracts every
// `id: '…'` declaration, and emits unitids.txt: one ID per line, sorted. The
// snapshot is consumed via //go:embed in pkg/plugin/unit_map_test.go to validate
// that every entry in unitSymbolToGrafanaID maps to a real Grafana ID.
//
// Refresh: cd pkg/plugin/grafanaunits && go run gen.go <grafana-tag> > unitids.txt
// (e.g. go run gen.go v12.1.0 > unitids.txt).
//
// v12.1.0 is the floor because plugin.json's grafanaDependency is >=12.1.0:
// a value valid in a later patch but absent in 12.1 would silently render with
// no unit for users still on 12.1. The unit registry is invariant across
// v12.1.0–v12.4.x (verified by diffing categories.ts between tags), so pinning
// the floor is sufficient.
//
// Upstream copyright Grafana Labs, licensed Apache-2.0. The emitted file contains
// only unit-ID strings extracted from the value-format registry — none of the
// upstream code, structure, or expression is reproduced.
package main

import (
	"bytes"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"slices"
)

const upstreamURLFmt = "https://raw.githubusercontent.com/grafana/grafana/%s/packages/grafana-data/src/valueFormats/categories.ts"

// idPattern matches every `id: '<id>'` declaration in categories.ts; upstream
// uses this exact form on every format entry.
var idPattern = regexp.MustCompile(`id: '([^']+)'`)

func main() {
	log.SetFlags(0)
	log.SetPrefix("gen: ")
	if len(os.Args) != 2 {
		log.Fatalf("usage: go run gen.go <grafana-tag>  (e.g. v12.1.0)")
	}
	tag := os.Args[1]
	url := fmt.Sprintf(upstreamURLFmt, tag)

	resp, err := http.Get(url)
	if err != nil {
		log.Fatalf("fetch %s: %v", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("fetch %s: %s", url, resp.Status)
	}
	src, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("read body: %v", err)
	}

	matches := idPattern.FindAllSubmatch(src, -1)
	if len(matches) == 0 {
		log.Fatalf("no `id: '…'` matches in %s — upstream format may have changed", url)
	}
	ids := make([]string, 0, len(matches))
	for _, m := range matches {
		ids = append(ids, string(m[1]))
	}
	slices.Sort(ids)
	ids = slices.Compact(ids)

	var out bytes.Buffer
	fmt.Fprintf(&out, "# Code generated by gen.go; DO NOT EDIT.\n")
	fmt.Fprintf(&out, "# Source: grafana/grafana@%s\n", tag)
	fmt.Fprintf(&out, "#   %s\n", url)
	for _, id := range ids {
		out.WriteString(id)
		out.WriteByte('\n')
	}

	if _, err := os.Stdout.Write(out.Bytes()); err != nil {
		log.Fatalf("write stdout: %v", err)
	}
	log.Printf("emitted %d IDs from grafana/grafana@%s", len(ids), tag)
}
